services:
  server:
    container_name: server
    restart: always
    build: .
    ports:
      - "8080:3030"
    links:
      - mongodb
    volumes: 
      - .:/usr/src/app
    env_file:
      - .env

  mongodb:
    container_name: mongodatabase
    image: mongo
    ports:
      - "27019:27017"
    volumes:
      - ./backup:/docker-entrypoint-initdb.d
      - ./data:/data/db
    restart: always
